targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-gnu" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"
ignore = [
    # we're never going to escape time v1
    "RUSTSEC-2020-0071"
]

[bans]
multiple-versions = "allow" # three versions of time gambit
wildcards = "deny"
highlight = "all"
deny = []
skip = []

[licenses]
unlicensed = "deny"
allow = ["Apache-2.0", "0BSD", "BSD-2-Clause", "BSD-3-Clause", "ISC", "MIT", "MPL-2.0", "Zlib", "LicenseRef-ring", "LicenseRef-webpki"]
deny = []
copyleft = "deny" # we allow MPL since it's a weak copyleft and still lets us sublicense
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.95

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[[licenses.clarify]]
name = "webpki"
expression = "LicenseRef-webpki"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
